-- DO Szerver Partner Azonosítók Szinkronizáló SQL script
-- Generálva a lokális tesztkörnyezetből

-- 1. AKTÍV AZONOSÍTÓK BEÁLLÍTÁSA
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('AGROPONIENTE') AND partner_id IN (SELECT id FROM partners WHERE name = 'AGROPONIENTE S.A.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('OLASO') AND partner_id IN (SELECT id FROM partners WHERE name = 'OLASO');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('WRAPPING') AND partner_id IN (SELECT id FROM partners WHERE name = 'WRAPPING');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('ESCOBI') AND partner_id IN (SELECT id FROM partners WHERE name = 'ESCOBI');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('AGROPONIENTE NIJAR') AND partner_id IN (SELECT id FROM partners WHERE name = 'AGROPONIENTE NIJAR');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('CASI AIRPORT') AND partner_id IN (SELECT id FROM partners WHERE name = 'CASI AIRPORT');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('AXARFRUIT') AND partner_id IN (SELECT id FROM partners WHERE name = 'Axarfruit');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('EXPOALMA') AND partner_id IN (SELECT id FROM partners WHERE name = 'Expoalma S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('COMPAGRI') AND partner_id IN (SELECT id FROM partners WHERE name = 'COMPAGRI');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('CASI AEROPORTO') AND partner_id IN (SELECT id FROM partners WHERE name = 'CASI AEROPORTO');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('AGROPONIENTE NATURAL') AND partner_id IN (SELECT id FROM partners WHERE name = 'Agroponiente Natural Produce S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('HANKA') AND partner_id IN (SELECT id FROM partners WHERE name = 'HANKA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('ENGELAN') AND partner_id IN (SELECT id FROM partners WHERE name = 'ENGELAN');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('KUSEK') AND partner_id IN (SELECT id FROM partners WHERE name = 'KUSEK');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('KUSEK') AND partner_id IN (SELECT id FROM partners WHERE name = 'KUSEK');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('R&M') AND partner_id IN (SELECT id FROM partners WHERE name = 'R&M');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('R&M') AND partner_id IN (SELECT id FROM partners WHERE name = 'R&M');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('SPAR HU') AND partner_id IN (SELECT id FROM partners WHERE name = 'SPAR HU');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('SPAR HU') AND partner_id IN (SELECT id FROM partners WHERE name = 'SPAR HU');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('CASI') AND partner_id IN (SELECT id FROM partners WHERE name = 'CASI');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('CASI PARTIDORES') AND partner_id IN (SELECT id FROM partners WHERE name = 'CASI PARTIDORES');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('ESCOFRESH') AND partner_id IN (SELECT id FROM partners WHERE name = 'ESCOFRESH');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('FRANIAL') AND partner_id IN (SELECT id FROM partners WHERE name = 'FRANIAL');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('FRESSAN') AND partner_id IN (SELECT id FROM partners WHERE name = 'FRESSAN');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('FRUTAS GAVA') AND partner_id IN (SELECT id FROM partners WHERE name = 'FRUTAS GAVA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('GALLARDO') AND partner_id IN (SELECT id FROM partners WHERE name = 'GALLARDO');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('GREEN QUALITY') AND partner_id IN (SELECT id FROM partners WHERE name = 'GREEN QUALITY');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('VEGACANADA') AND partner_id IN (SELECT id FROM partners WHERE name = 'VEGACANADA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('CORD') AND partner_id IN (SELECT id FROM partners WHERE name = 'CORD');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('CORD') AND partner_id IN (SELECT id FROM partners WHERE name = 'CORD');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('EUROGROUP ESPANA') AND partner_id IN (SELECT id FROM partners WHERE name = 'EUROGROUP ESPANA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('EXOTIC FRESH') AND partner_id IN (SELECT id FROM partners WHERE name = 'EXOTIC FRESH');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('EXOTIC FRESH') AND partner_id IN (SELECT id FROM partners WHERE name = 'EXOTIC FRESH');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('GHU') AND partner_id IN (SELECT id FROM partners WHERE name = 'GHU');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('GHU') AND partner_id IN (SELECT id FROM partners WHERE name = 'GHU');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('AGRONERVION') AND partner_id IN (SELECT id FROM partners WHERE name = 'Agronervion, S.L.U.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('BERTIPACK') AND partner_id IN (SELECT id FROM partners WHERE name = 'Bertipack, S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('GEMÜSERING') AND partner_id IN (SELECT id FROM partners WHERE name = 'GEMÜSERING');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('GEMÜSERING') AND partner_id IN (SELECT id FROM partners WHERE name = 'GEMÜSERING');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('GREENCOOP') AND partner_id IN (SELECT id FROM partners WHERE name = 'GREENCOOP');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('GREENCOOP') AND partner_id IN (SELECT id FROM partners WHERE name = 'GREENCOOP');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('LEVENTE') AND partner_id IN (SELECT id FROM partners WHERE name = 'LEVENTE');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('LEVENTE') AND partner_id IN (SELECT id FROM partners WHERE name = 'LEVENTE');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('ROMÁNIA') AND partner_id IN (SELECT id FROM partners WHERE name = 'ROMÁNIA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('ROMÁNIA') AND partner_id IN (SELECT id FROM partners WHERE name = 'ROMÁNIA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('VILLAFRUT') AND partner_id IN (SELECT id FROM partners WHERE name = 'VILLAFRUT SRL');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('ALDI AT') AND partner_id IN (SELECT id FROM partners WHERE name = 'ALDI AT');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('KV LOGISTIKA') AND partner_id IN (SELECT id FROM partners WHERE name = 'KV LOGISTIKA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('AZAFAMA') AND partner_id IN (SELECT id FROM partners WHERE name = 'Azafama Tropical LDA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('BALCANIC FOOD') AND partner_id IN (SELECT id FROM partners WHERE name = 'Balcanic Food Trade Company');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('CRETAN ROOT') AND partner_id IN (SELECT id FROM partners WHERE name = 'Cretan Root');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('CRETAN ROOT') AND partner_id IN (SELECT id FROM partners WHERE name = 'Cretan Root');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('CRETAN ROOT') AND partner_id IN (SELECT id FROM partners WHERE name = 'Cretan Root');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('GAVA') AND partner_id IN (SELECT id FROM partners WHERE name = 'GAVA TXEQUIA S.R.O.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('GAVA') AND partner_id IN (SELECT id FROM partners WHERE name = 'GAVA TXEQUIA S.R.O.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('GAVA') AND partner_id IN (SELECT id FROM partners WHERE name = 'GAVA TXEQUIA S.R.O.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('KOPFSALAT') AND partner_id IN (SELECT id FROM partners WHERE name = 'KOPFSALAT TRADE SL.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('KOPFSALAT') AND partner_id IN (SELECT id FROM partners WHERE name = 'KOPFSALAT TRADE SL.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('KOPFSALAT') AND partner_id IN (SELECT id FROM partners WHERE name = 'KOPFSALAT TRADE SL.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('HYBRID FRUIT') AND partner_id IN (SELECT id FROM partners WHERE name = 'HYBRID FRUIT Kft.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('KERMOR') AND partner_id IN (SELECT id FROM partners WHERE name = 'Kermor Bt.......');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('CHERY TIM') AND partner_id IN (SELECT id FROM partners WHERE name = 'CHERY TIM DISTRIBUTION SRL.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('CHERY TIM') AND partner_id IN (SELECT id FROM partners WHERE name = 'CHERY TIM DISTRIBUTION SRL.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('COCO FRUITS') AND partner_id IN (SELECT id FROM partners WHERE name = 'Coco Fruits and Vegetables S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('MK FRESH') AND partner_id IN (SELECT id FROM partners WHERE name = 'MK FRESH PRODUCT SARL');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('MK FRESH PRODUCT') AND partner_id IN (SELECT id FROM partners WHERE name = 'MK FRESH PRODUCT SARL');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('SHEBA FRESH') AND partner_id IN (SELECT id FROM partners WHERE name = 'SHEBA Fresh');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('TOMATO-AL') AND partner_id IN (SELECT id FROM partners WHERE name = 'Tomato-Al');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('TOMATO-AL') AND partner_id IN (SELECT id FROM partners WHERE name = 'Tomato-Al');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('RONI') AND partner_id IN (SELECT id FROM partners WHERE name = 'Roni Cargo Kft.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('AGRICOLA NEJITE') AND partner_id IN (SELECT id FROM partners WHERE name = 'Agricola Nejite, S.L');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('ECOINVER EXPORT') AND partner_id IN (SELECT id FROM partners WHERE name = 'Ecoinver Export S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('DELGAFRUITS') AND partner_id IN (SELECT id FROM partners WHERE name = 'Delgafruits S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('DG69') AND partner_id IN (SELECT id FROM partners WHERE name = 'DG 69, d.o.o., Vrhnika');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('DG69') AND partner_id IN (SELECT id FROM partners WHERE name = 'DG 69, d.o.o., Vrhnika');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('VELASGRO') AND partner_id IN (SELECT id FROM partners WHERE name = 'Velasgro S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('ANTON DÜRBECK') AND partner_id IN (SELECT id FROM partners WHERE name = 'Anton Dürbeck GmbH');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('ANTON DÜRBECK') AND partner_id IN (SELECT id FROM partners WHERE name = 'Anton Dürbeck GmbH');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('AGRIFA LOGISTIC') AND partner_id IN (SELECT id FROM partners WHERE name = 'AGRIFA LOGISTIC');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('CASAS ROYES') AND partner_id IN (SELECT id FROM partners WHERE name = 'CASAS ROYES EXPORT S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('CASAS ROYES') AND partner_id IN (SELECT id FROM partners WHERE name = 'CASAS ROYES EXPORT S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('CLARA') AND partner_id IN (SELECT id FROM partners WHERE name = 'CLARA EXPORT, S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('FA. DE JONG') AND partner_id IN (SELECT id FROM partners WHERE name = 'Fa. De Jong - Fruit');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('GLOBAL BERRY') AND partner_id IN (SELECT id FROM partners WHERE name = 'Global Berry S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('GLOBAL BERRY') AND partner_id IN (SELECT id FROM partners WHERE name = 'Global Berry S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('IDEAL FRUITS') AND partner_id IN (SELECT id FROM partners WHERE name = 'Ideal Fruits, S.l.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('IDEAL FRUITS') AND partner_id IN (SELECT id FROM partners WHERE name = 'Ideal Fruits, S.l.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('LA CALIFORNIA') AND partner_id IN (SELECT id FROM partners WHERE name = 'LA CALIFORNIA TRADING ESPANA SL.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('OLYMPIC FRUIT') AND partner_id IN (SELECT id FROM partners WHERE name = 'Olympic Fruit B.V.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('OLYMPIC FRUIT') AND partner_id IN (SELECT id FROM partners WHERE name = 'Olympic Fruit B.V.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('SMART') AND partner_id IN (SELECT id FROM partners WHERE name = 'Smart Fruits S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('EUROGROUP ESPANA') AND partner_id IN (SELECT id FROM partners WHERE name = 'EUROGROUP ESPANA FRUTAS Y VERDURAS S.A.U.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('ESCOBAR') AND partner_id IN (SELECT id FROM partners WHERE name = 'Escobar Reyes, S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('KOMPAGRI') AND partner_id IN (SELECT id FROM partners WHERE name = 'KOMPAGRI ESPANA SL');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('MALENO Y TORRES') AND partner_id IN (SELECT id FROM partners WHERE name = 'Maleno Y Torres Exportación S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('MALENO') AND partner_id IN (SELECT id FROM partners WHERE name = 'Maleno Y Torres Exportación S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('AGESCO') AND partner_id IN (SELECT id FROM partners WHERE name = 'AGESCO S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('AGESCO') AND partner_id IN (SELECT id FROM partners WHERE name = 'AGESCO S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('ECOINVER BIO') AND partner_id IN (SELECT id FROM partners WHERE name = 'Ecoinver Bio S.L');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('ESMAR') AND partner_id IN (SELECT id FROM partners WHERE name = 'Esmar Frutas Imp-Exp. SL');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('FAUS DURA') AND partner_id IN (SELECT id FROM partners WHERE name = 'Faus Dura S.A.S.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('FRUCTUS') AND partner_id IN (SELECT id FROM partners WHERE name = 'Fructus Trade');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('FRUBALMED') AND partner_id IN (SELECT id FROM partners WHERE name = 'FRUBALMED SLU');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('FRUBALMED') AND partner_id IN (SELECT id FROM partners WHERE name = 'FRUBALMED SLU');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('FRUBALMED') AND partner_id IN (SELECT id FROM partners WHERE name = 'FRUBALMED SLU');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('BOGNÁR') AND partner_id IN (SELECT id FROM partners WHERE name = 'Bognár Transport Korlátolt Felelősségű Társaság');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('BILEK') AND partner_id IN (SELECT id FROM partners WHERE name = 'BILEK');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('BILEK') AND partner_id IN (SELECT id FROM partners WHERE name = 'BILEK');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('BILEK') AND partner_id IN (SELECT id FROM partners WHERE name = 'BILEK');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('BILEK LEVI') AND partner_id IN (SELECT id FROM partners WHERE name = 'BILEK');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('GREENYARD') AND partner_id IN (SELECT id FROM partners WHERE name = 'Greenyard Fresh Spain SA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('GREENYARD') AND partner_id IN (SELECT id FROM partners WHERE name = 'Greenyard Fresh Spain SA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('BUGYI FERENC') AND partner_id IN (SELECT id FROM partners WHERE name = 'Bugyi Ferenc Kft.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('GYÜMÖLCSÉRT') AND partner_id IN (SELECT id FROM partners WHERE name = 'Gyümölcsért Kft.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('GYÜMÖLCSÉRT') AND partner_id IN (SELECT id FROM partners WHERE name = 'Gyümölcsért Kft.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('HISPA GROUP') AND partner_id IN (SELECT id FROM partners WHERE name = 'Hispa Group Spain, S.L');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('HOFER') AND partner_id IN (SELECT id FROM partners WHERE name = 'HOFER Trgovina d.o.o.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('BÉKA') AND partner_id IN (SELECT id FROM partners WHERE name = 'BÉKA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('INDASOL') AND partner_id IN (SELECT id FROM partners WHERE name = 'INDASOL S.A.T.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('CROSS') AND partner_id IN (SELECT id FROM partners WHERE name = 'CROSS');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('KOPALMERIA') AND partner_id IN (SELECT id FROM partners WHERE name = 'KOPALMERIA S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('CSÍK ZOLTÁN') AND partner_id IN (SELECT id FROM partners WHERE name = 'CSÍK ZOLTÁN');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('LA PIRUJITA') AND partner_id IN (SELECT id FROM partners WHERE name = 'La Pirujita SCA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('LEHMANN & TROOST') AND partner_id IN (SELECT id FROM partners WHERE name = 'LEHMANN & TROOST B.V.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('LEHMANN & TROOST') AND partner_id IN (SELECT id FROM partners WHERE name = 'LEHMANN & TROOST B.V.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('MANEKI') AND partner_id IN (SELECT id FROM partners WHERE name = 'Maneki Neko Group s.r.o.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('Csávó') AND partner_id IN (SELECT id FROM partners WHERE name = 'Csávó');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('KRISTÓF PÉTER') AND partner_id IN (SELECT id FROM partners WHERE name = 'KRISTÓF PÉTER');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('MÜLLER') AND partner_id IN (SELECT id FROM partners WHERE name = 'Müller-Transporte Gesellschaft m.b.H.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('NATURNAR') AND partner_id IN (SELECT id FROM partners WHERE name = 'NATURNAR KRYLUAN SL.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('NATURINDA') AND partner_id IN (SELECT id FROM partners WHERE name = 'NATURINDA, SLNE');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('KRISZTIÁN') AND partner_id IN (SELECT id FROM partners WHERE name = 'KRISZTIÁN');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('KUONI') AND partner_id IN (SELECT id FROM partners WHERE name = 'KUONI TRADE KFT.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('ORANGE') AND partner_id IN (SELECT id FROM partners WHERE name = 'Orange Factory Kft.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('PAP JÓZSEFNÉ') AND partner_id IN (SELECT id FROM partners WHERE name = 'Pap Józsefné');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('KV LOG') AND partner_id IN (SELECT id FROM partners WHERE name = 'KV LOG');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('VERMIO') AND partner_id IN (SELECT id FROM partners WHERE name = 'VERMIO');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('VERMIO') AND partner_id IN (SELECT id FROM partners WHERE name = 'VERMIO');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('VERMION') AND partner_id IN (SELECT id FROM partners WHERE name = 'VERMION');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('VERMION') AND partner_id IN (SELECT id FROM partners WHERE name = 'VERMION');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('RELAX FRUITS') AND partner_id IN (SELECT id FROM partners WHERE name = 'Relax Fruits And Vegetables S.L');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('SAN NICOLA') AND partner_id IN (SELECT id FROM partners WHERE name = 'SAN NICOLA GROUP S.R.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('SAN NICOLA') AND partner_id IN (SELECT id FROM partners WHERE name = 'SAN NICOLA GROUP S.R.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('SAN NICOLA') AND partner_id IN (SELECT id FROM partners WHERE name = 'SAN NICOLA GROUP S.R.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('SENOR TOMATE') AND partner_id IN (SELECT id FROM partners WHERE name = 'Senor Tomate Kereskedelmi Korlátolt Felelősségű Társaság');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('SOLHERBS') AND partner_id IN (SELECT id FROM partners WHERE name = 'SOLHERBS, S.L.U.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('SOÓS') AND partner_id IN (SELECT id FROM partners WHERE name = 'Soós Mihályné');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('SYLVAN') AND partner_id IN (SELECT id FROM partners WHERE name = 'Sylvan Hungária Zrt.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('SYLVAN') AND partner_id IN (SELECT id FROM partners WHERE name = 'Sylvan Hungária Zrt.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('THERMO FRUCHT') AND partner_id IN (SELECT id FROM partners WHERE name = 'THERMO FRUCHT Kft.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('TOLEDANO HORTICOLA') AND partner_id IN (SELECT id FROM partners WHERE name = 'Toledano Horticola S.L');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('VICASOL') AND partner_id IN (SELECT id FROM partners WHERE name = 'Vicasol S. Coop. And.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('VIRÁG') AND partner_id IN (SELECT id FROM partners WHERE name = 'Virág Sándor');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('PANNON') AND partner_id IN (SELECT id FROM partners WHERE name = 'Pannon Fruit Cargo Kft.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('PANNONFRUIT') AND partner_id IN (SELECT id FROM partners WHERE name = 'PANNONFRUIT');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('PET-IMPEX') AND partner_id IN (SELECT id FROM partners WHERE name = 'PET-IMPEX');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('POLAND') AND partner_id IN (SELECT id FROM partners WHERE name = 'POLAND');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('POLSKA') AND partner_id IN (SELECT id FROM partners WHERE name = 'POLSKA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('ALL FRESH') AND partner_id IN (SELECT id FROM partners WHERE name = 'All Fresh Logistics GmbH');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('ANTIGONE') AND partner_id IN (SELECT id FROM partners WHERE name = 'ANTIGONE');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('ATRANS') AND partner_id IN (SELECT id FROM partners WHERE name = 'ATRANS');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('BVT') AND partner_id IN (SELECT id FROM partners WHERE name = 'BVT');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('CALICHE') AND partner_id IN (SELECT id FROM partners WHERE name = 'CALICHE');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('CHAMPION') AND partner_id IN (SELECT id FROM partners WHERE name = 'CHAMPION');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('CHER') AND partner_id IN (SELECT id FROM partners WHERE name = 'CHER');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('CSACSI') AND partner_id IN (SELECT id FROM partners WHERE name = 'CSACSI');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('CSÍK ZOLI') AND partner_id IN (SELECT id FROM partners WHERE name = 'CSÍK ZOLI');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('Citrom 10kg') AND partner_id IN (SELECT id FROM partners WHERE name = 'Citrom 10kg');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('FARAON') AND partner_id IN (SELECT id FROM partners WHERE name = 'FARAON EGIPCIO SL');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('FARAON') AND partner_id IN (SELECT id FROM partners WHERE name = 'FARAON EGIPCIO SL');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('DIANIA') AND partner_id IN (SELECT id FROM partners WHERE name = 'DIANIA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('DINAMO') AND partner_id IN (SELECT id FROM partners WHERE name = 'DINAMO');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('DINAMÓ') AND partner_id IN (SELECT id FROM partners WHERE name = 'DINAMÓ');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('DRAGAN') AND partner_id IN (SELECT id FROM partners WHERE name = 'DRAGAN');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('DÉLBALATON TÉSZ') AND partner_id IN (SELECT id FROM partners WHERE name = 'DÉLBALATON TÉSZ');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('Dóri') AND partner_id IN (SELECT id FROM partners WHERE name = 'Dóri');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('ESKADA') AND partner_id IN (SELECT id FROM partners WHERE name = 'ESKADA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('EURO MILAN') AND partner_id IN (SELECT id FROM partners WHERE name = 'EURO MILAN');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('FER TRANS') AND partner_id IN (SELECT id FROM partners WHERE name = 'Fer Trans ''96 Szállítási Szolgáltató Korlátolt Felelősségű Társaság');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('FRESCO TRANS') AND partner_id IN (SELECT id FROM partners WHERE name = 'Fresco Trans');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('FRIGOSPED') AND partner_id IN (SELECT id FROM partners WHERE name = 'FRIGOSPED');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('FUSTER') AND partner_id IN (SELECT id FROM partners WHERE name = 'FUSTER');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('G ROAD') AND partner_id IN (SELECT id FROM partners WHERE name = 'G ROAD');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('G-ROAD') AND partner_id IN (SELECT id FROM partners WHERE name = 'G-ROAD Kft.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('GARTNER') AND partner_id IN (SELECT id FROM partners WHERE name = 'GARTNER');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('HANK') AND partner_id IN (SELECT id FROM partners WHERE name = 'HANK');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('HANKÓ') AND partner_id IN (SELECT id FROM partners WHERE name = 'HANKÓ');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('HILLTOP') AND partner_id IN (SELECT id FROM partners WHERE name = 'Hilltop Logisztikai Kft');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('HRT') AND partner_id IN (SELECT id FROM partners WHERE name = 'HRT');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('HZ') AND partner_id IN (SELECT id FROM partners WHERE name = 'HZ');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('HZ LOGISTICS') AND partner_id IN (SELECT id FROM partners WHERE name = 'HZ LOGISTICS');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('IMANOV') AND partner_id IN (SELECT id FROM partners WHERE name = 'IMANOV');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('IMANOV / KÓNYA') AND partner_id IN (SELECT id FROM partners WHERE name = 'IMANOV / KÓNYA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('INTERTRANS') AND partner_id IN (SELECT id FROM partners WHERE name = 'INTERTRANS');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('JOKER') AND partner_id IN (SELECT id FROM partners WHERE name = 'JOKER');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('JUICE') AND partner_id IN (SELECT id FROM partners WHERE name = 'JUICE');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('KARKAVITSAS') AND partner_id IN (SELECT id FROM partners WHERE name = 'KARKAVITSAS');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('KARKAVITSAS') AND partner_id IN (SELECT id FROM partners WHERE name = 'KARKAVITSAS');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('KESSEC') AND partner_id IN (SELECT id FROM partners WHERE name = 'KESSEC');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('KI-JU-TÓ') AND partner_id IN (SELECT id FROM partners WHERE name = 'Ki-Ju-Tó Szolgáltató És Kereskedelmi Korlátolt Felelősségű Társaság');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('KIJUTÓ') AND partner_id IN (SELECT id FROM partners WHERE name = 'KIJUTÓ');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('KOZAK') AND partner_id IN (SELECT id FROM partners WHERE name = 'KOZAK');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('AGROSTAR') AND partner_id IN (SELECT id FROM partners WHERE name = 'AGROSTAR VEGETABLES KFT.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('ARVEN') AND partner_id IN (SELECT id FROM partners WHERE name = 'ARVEN PAZARLAMA LTD.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('GAVA POLSKA') AND partner_id IN (SELECT id FROM partners WHERE name = 'Gava Polska Sp. z o.o.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('GAVA POLSKA') AND partner_id IN (SELECT id FROM partners WHERE name = 'Gava Polska Sp. z o.o.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('GRUPO NATURAL') AND partner_id IN (SELECT id FROM partners WHERE name = 'GRUPO NATURAL DE EXPORTACIÓN Y PROD.DECITRICOS Y FRUTAS S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('GRUPO NATURAL') AND partner_id IN (SELECT id FROM partners WHERE name = 'GRUPO NATURAL DE EXPORTACIÓN Y PROD.DECITRICOS Y FRUTAS S.L.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('KÁDÁR') AND partner_id IN (SELECT id FROM partners WHERE name = 'Kádár Trans Sped Korlátolt Felelősségű Társaság');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('LIVIU') AND partner_id IN (SELECT id FROM partners WHERE name = 'LIVIU');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('LIVIU') AND partner_id IN (SELECT id FROM partners WHERE name = 'LIVIU');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('LOGISTICHOME') AND partner_id IN (SELECT id FROM partners WHERE name = 'LOGISTICHOME');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('LOGISTICSHOME') AND partner_id IN (SELECT id FROM partners WHERE name = 'LOGISTICSHOME');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('LUI') AND partner_id IN (SELECT id FROM partners WHERE name = 'LUI');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('MASEVERDE') AND partner_id IN (SELECT id FROM partners WHERE name = 'MASEVERDE');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('MESAVERDE') AND partner_id IN (SELECT id FROM partners WHERE name = 'MESAVERDE KFT.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('MANDERSLOOT') AND partner_id IN (SELECT id FROM partners WHERE name = 'Mandersloot Expeditiebedrijf B.V.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('MANDERSLOOT') AND partner_id IN (SELECT id FROM partners WHERE name = 'Mandersloot Expeditiebedrijf B.V.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('MANDERSLOOT') AND partner_id IN (SELECT id FROM partners WHERE name = 'Mandersloot Expeditiebedrijf B.V.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('NAGEL') AND partner_id IN (SELECT id FROM partners WHERE name = 'NAGEL HUNGÁRIA KFT.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('NH CARGO') AND partner_id IN (SELECT id FROM partners WHERE name = 'NH Cargo Kft');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('NÁPOLYI ZOLI') AND partner_id IN (SELECT id FROM partners WHERE name = 'NÁPOLYI ZOLI');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('P TRANS') AND partner_id IN (SELECT id FROM partners WHERE name = 'P TRANS');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('PÉCSI A./GIRTEKA') AND partner_id IN (SELECT id FROM partners WHERE name = 'PÉCSI A./GIRTEKA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('RAINBOW') AND partner_id IN (SELECT id FROM partners WHERE name = 'RAINBOW');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('REMONA') AND partner_id IN (SELECT id FROM partners WHERE name = 'REMONA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('RENACRIS') AND partner_id IN (SELECT id FROM partners WHERE name = 'RENACRIS');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('ROSE TRADE') AND partner_id IN (SELECT id FROM partners WHERE name = 'ROSE TRADE');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('S TRANS') AND partner_id IN (SELECT id FROM partners WHERE name = 'S TRANS');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('S-TRANS') AND partner_id IN (SELECT id FROM partners WHERE name = 'S-TRANS');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('S-TRANSPORT') AND partner_id IN (SELECT id FROM partners WHERE name = 'S-Transport');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('S.T.I') AND partner_id IN (SELECT id FROM partners WHERE name = 'S.T.I');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('S.T.I.') AND partner_id IN (SELECT id FROM partners WHERE name = 'S.T.I. Hungary  Szállítmányozási Korlátolt Felelősségű Társaság');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('SARTO KFT') AND partner_id IN (SELECT id FROM partners WHERE name = 'SARTO KFT');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('SCANTRANS') AND partner_id IN (SELECT id FROM partners WHERE name = 'Scantrans Kanizsa Kft.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('SEED') AND partner_id IN (SELECT id FROM partners WHERE name = 'Seed Trans Korlátolt Felelősségű Társaság');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('SERGIO') AND partner_id IN (SELECT id FROM partners WHERE name = 'SERGIO');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('SHEBA') AND partner_id IN (SELECT id FROM partners WHERE name = 'SHEBA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('SHEBA') AND partner_id IN (SELECT id FROM partners WHERE name = 'SHEBA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('SOÓS TRANS') AND partner_id IN (SELECT id FROM partners WHERE name = 'SOÓS TRANS');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('STI') AND partner_id IN (SELECT id FROM partners WHERE name = 'STI');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('STÉ. ANATYS') AND partner_id IN (SELECT id FROM partners WHERE name = 'STÉ. ANATYS');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('SWISS') AND partner_id IN (SELECT id FROM partners WHERE name = 'Swiss Temp Logistics GmbH');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('SZABÓ FERI') AND partner_id IN (SELECT id FROM partners WHERE name = 'SZABÓ FERI');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('SZABÓ KATA') AND partner_id IN (SELECT id FROM partners WHERE name = 'SZABÓ KATA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('SZENTI') AND partner_id IN (SELECT id FROM partners WHERE name = 'SZENTI TRANS KFT.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('SZÉKESI') AND partner_id IN (SELECT id FROM partners WHERE name = 'Székesi Kft.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('TARRAGONA') AND partner_id IN (SELECT id FROM partners WHERE name = 'TARRAGONA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('THERMO FRUCHT KFT') AND partner_id IN (SELECT id FROM partners WHERE name = 'THERMO FRUCHT KFT');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('TOMATO AL') AND partner_id IN (SELECT id FROM partners WHERE name = 'TOMATO AL');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('TOOMATO-AL') AND partner_id IN (SELECT id FROM partners WHERE name = 'TOOMATO-AL');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('TRANS FLORA') AND partner_id IN (SELECT id FROM partners WHERE name = 'TRANS FLORA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('TRANS SPED') AND partner_id IN (SELECT id FROM partners WHERE name = 'TRANS SPED');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('TRANS-SPED') AND partner_id IN (SELECT id FROM partners WHERE name = 'Trans-Sped Kft.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('TWINS TRANS') AND partner_id IN (SELECT id FROM partners WHERE name = 'TWINS TRANS');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('TÓTH FRIGO') AND partner_id IN (SELECT id FROM partners WHERE name = 'TÓTH FRIGO');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('UZ TRANS') AND partner_id IN (SELECT id FROM partners WHERE name = 'UZ TRANS');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('V & B CARGO') AND partner_id IN (SELECT id FROM partners WHERE name = 'V & B CARGO');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('VASKÓ') AND partner_id IN (SELECT id FROM partners WHERE name = 'VASKÓ');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('KÓNYA') AND partner_id IN (SELECT id FROM partners WHERE name = 'KÓNYA ZOLTÁNNÉ');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('KÓNYA') AND partner_id IN (SELECT id FROM partners WHERE name = 'KÓNYA ZOLTÁNNÉ');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('KÓNYA') AND partner_id IN (SELECT id FROM partners WHERE name = 'KÓNYA ZOLTÁNNÉ');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('VITA FRUIT') AND partner_id IN (SELECT id FROM partners WHERE name = 'Vita Fruit SP. Z.O.O.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('VITAFRUIT') AND partner_id IN (SELECT id FROM partners WHERE name = 'VITAFRUIT');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('VITAFRUIT') AND partner_id IN (SELECT id FROM partners WHERE name = 'VITAFRUIT');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('WABERER''S') AND partner_id IN (SELECT id FROM partners WHERE name = 'Waberer''s International Nyilvánosan Működő Részvénytársaság');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('WABERERS') AND partner_id IN (SELECT id FROM partners WHERE name = 'WABERERS');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('WINDBAHN') AND partner_id IN (SELECT id FROM partners WHERE name = 'WINDBAHN KFT.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('XENIA') AND partner_id IN (SELECT id FROM partners WHERE name = 'XENIA');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('ZAJAC') AND partner_id IN (SELECT id FROM partners WHERE name = 'ZAJAC');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('ZERO') AND partner_id IN (SELECT id FROM partners WHERE name = 'ZERO TRADE Kft.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('VERMION FRESH') AND partner_id IN (SELECT id FROM partners WHERE name = 'Vermion Fresh S.A.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('DERBY') AND partner_id IN (SELECT id FROM partners WHERE name = 'DERBY FRUIT TRADE KFT.');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('EUROGROUP DEUTSCHLAND') AND partner_id IN (SELECT id FROM partners WHERE name = 'Eurogroup Deutschland Gmbh');
UPDATE partner_identifiers SET is_inactive = false WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('EUROGROUP DEUTSCHLAND') AND partner_id IN (SELECT id FROM partners WHERE name = 'Eurogroup Deutschland Gmbh');

-- 2. INAKTÍV (TÖRTÉNELMI / DUPLIKÁLT) AZONOSÍTÓK BEÁLLÍTÁSA
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('AXAFRUIT') AND partner_id IN (SELECT id FROM partners WHERE name = 'Axarfruit');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('DG69') AND partner_id IN (SELECT id FROM partners WHERE name = 'DG69');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('DG69') AND partner_id IN (SELECT id FROM partners WHERE name = 'DG69');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('AGROPONIENTE NIJAR') AND partner_id IN (SELECT id FROM partners WHERE name = 'Agroponiente Natural Produce S.L.');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('AGROPONIENTE') AND partner_id IN (SELECT id FROM partners WHERE name = 'Agroponiente Natural Produce S.L.');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('AGRPONIENTE') AND partner_id IN (SELECT id FROM partners WHERE name = 'Agroponiente Natural Produce S.L.');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('CASI AIRPORT') AND partner_id IN (SELECT id FROM partners WHERE name = 'CASI');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('CASI AEROPORTO') AND partner_id IN (SELECT id FROM partners WHERE name = 'CASI');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('CASI ARIPORT') AND partner_id IN (SELECT id FROM partners WHERE name = 'CASI');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('GAVA') AND partner_id IN (SELECT id FROM partners WHERE name = 'FRUTAS GAVA');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('GAVA') AND partner_id IN (SELECT id FROM partners WHERE name = 'FRUTAS GAVA');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('GAVA') AND partner_id IN (SELECT id FROM partners WHERE name = 'FRUTAS GAVA');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('EUROGROUP ESPANA') AND partner_id IN (SELECT id FROM partners WHERE name = 'EUROGROUP ESPANA');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('EUROGROUP ES') AND partner_id IN (SELECT id FROM partners WHERE name = 'EUROGROUP ESPANA');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('EUROGROUP') AND partner_id IN (SELECT id FROM partners WHERE name = 'EUROGROUP ESPANA');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('EUROGROUP ES') AND partner_id IN (SELECT id FROM partners WHERE name = 'EUROGROUP ESPANA');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('EUROGROUP') AND partner_id IN (SELECT id FROM partners WHERE name = 'EUROGROUP ESPANA');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('RONI') AND partner_id IN (SELECT id FROM partners WHERE name = 'Békési Veronika');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('BOGNÁR') AND partner_id IN (SELECT id FROM partners WHERE name = 'Bognárné Gyöngyösi Enikő');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('SMART') AND partner_id IN (SELECT id FROM partners WHERE name = 'BRAVOSMART Kft');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('DELGAFRUIT') AND partner_id IN (SELECT id FROM partners WHERE name = 'Delgafruits S.L.');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('OLYMPIC') AND partner_id IN (SELECT id FROM partners WHERE name = 'Olympic Fruit B.V.');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('OLYMPIC FRUITS') AND partner_id IN (SELECT id FROM partners WHERE name = 'Olympic Fruit B.V.');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('OLYMPIC') AND partner_id IN (SELECT id FROM partners WHERE name = 'Olympic Fruit B.V.');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('OLYMPIC FRUITS') AND partner_id IN (SELECT id FROM partners WHERE name = 'Olympic Fruit B.V.');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('COMPAGRI') AND partner_id IN (SELECT id FROM partners WHERE name = 'KOMPAGRI ESPANA SL');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('KÓNYA') AND partner_id IN (SELECT id FROM partners WHERE name = 'Kónya Trans Korlátolt Felelősségű Társaság');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('KÓNYA') AND partner_id IN (SELECT id FROM partners WHERE name = 'Kónya Trans Korlátolt Felelősségű Társaság');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('KÓNYA') AND partner_id IN (SELECT id FROM partners WHERE name = 'Kónya Trans Korlátolt Felelősségű Társaság');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('LEHMANN') AND partner_id IN (SELECT id FROM partners WHERE name = 'LEHMANN & TROOST B.V.');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('LEHMANN') AND partner_id IN (SELECT id FROM partners WHERE name = 'LEHMANN & TROOST B.V.');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('THERMO') AND partner_id IN (SELECT id FROM partners WHERE name = 'Thermonet Trade Kereskedelmi Korlátolt Felelősségű Társaság');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('THERMO') AND partner_id IN (SELECT id FROM partners WHERE name = 'Thermo Épitöipari Tervezö Szervezö És Kivitelezö Kft');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('PAP') AND partner_id IN (SELECT id FROM partners WHERE name = 'PAP');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('FRIGOSPED SK') AND partner_id IN (SELECT id FROM partners WHERE name = 'FRIGOSPED SK');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('HILTOP') AND partner_id IN (SELECT id FROM partners WHERE name = 'Hilltop Logisztikai Kft');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('HZ LOG') AND partner_id IN (SELECT id FROM partners WHERE name = 'HZ LOG');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('MANDRESLOOT') AND partner_id IN (SELECT id FROM partners WHERE name = 'Mandersloot Expeditiebedrijf B.V.');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('S TRANSPORT') AND partner_id IN (SELECT id FROM partners WHERE name = 'S TRANSPORT');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = 'Fuvarozók' AND UPPER(value) = UPPER('SWISS TEMP') AND partner_id IN (SELECT id FROM partners WHERE name = 'Swiss Temp Logistics GmbH');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Customer) Vevők' AND UPPER(value) = UPPER('EUROGROUP DE') AND partner_id IN (SELECT id FROM partners WHERE name = 'Eurogroup Deutschland Gmbh');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('EUROGROUP DE') AND partner_id IN (SELECT id FROM partners WHERE name = 'Eurogroup Deutschland Gmbh');
UPDATE partner_identifiers SET is_inactive = true WHERE id_type = '(Reference) Szállítók' AND UPPER(value) = UPPER('EURORGOUP DEUTSCHLAND') AND partner_id IN (SELECT id FROM partners WHERE name = 'Eurogroup Deutschland Gmbh');
