-- HIÁNYZÓ PARTNER AZONOSÍTÓK BEILLESZTÉSE DO SZERVEREN
BEGIN;

-- 1. OLASO és WRAPPING partnerek biztosítása
INSERT INTO partners (name, is_active, created_at, updated_at) SELECT 'OLASO', true, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM partners WHERE UPPER(name) = 'OLASO');
INSERT INTO partners (name, is_active, created_at, updated_at) SELECT 'WRAPPING', true, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM partners WHERE UPPER(name) = 'WRAPPING');

-- 2. Azonosítók társítása partner név alapján
INSERT INTO partner_identifiers (partner_id, id_type, value, created_at, updated_at) SELECT id, '(Customer) Vevők', 'BILEK', NOW(), NOW() FROM partners WHERE UPPER(name) = UPPER('BILEK') AND NOT EXISTS (SELECT 1 FROM partner_identifiers WHERE partner_id = partners.id AND id_type = '(Customer) Vevők' AND value = 'BILEK') LIMIT 1;
INSERT INTO partner_identifiers (partner_id, id_type, value, created_at, updated_at) SELECT id, '(Customer) Vevők', 'KÓNYA', NOW(), NOW() FROM partners WHERE UPPER(name) = UPPER('KÓNYA ZOLTÁNNÉ') AND NOT EXISTS (SELECT 1 FROM partner_identifiers WHERE partner_id = partners.id AND id_type = '(Customer) Vevők' AND value = 'KÓNYA') LIMIT 1;
INSERT INTO partner_identifiers (partner_id, id_type, value, created_at, updated_at) SELECT id, '(Reference) Szállítók', 'GAVA', NOW(), NOW() FROM partners WHERE UPPER(name) = UPPER('GAVA TXEQUIA S.R.O.') AND NOT EXISTS (SELECT 1 FROM partner_identifiers WHERE partner_id = partners.id AND id_type = '(Reference) Szállítók' AND value = 'GAVA') LIMIT 1;
INSERT INTO partner_identifiers (partner_id, id_type, value, created_at, updated_at) SELECT id, '(Reference) Szállítók', 'MALENO Y TORRES', NOW(), NOW() FROM partners WHERE UPPER(name) = UPPER('Maleno Y Torres Exportación S.L.') AND NOT EXISTS (SELECT 1 FROM partner_identifiers WHERE partner_id = partners.id AND id_type = '(Reference) Szállítók' AND value = 'MALENO Y TORRES') LIMIT 1;
INSERT INTO partner_identifiers (partner_id, id_type, value, created_at, updated_at) SELECT id, '(Reference) Szállítók', 'COMPAGRI', NOW(), NOW() FROM partners WHERE UPPER(name) = UPPER('KOMPAGRI ESPANA SL') AND NOT EXISTS (SELECT 1 FROM partner_identifiers WHERE partner_id = partners.id AND id_type = '(Reference) Szállítók' AND value = 'COMPAGRI') LIMIT 1;
INSERT INTO partner_identifiers (partner_id, id_type, value, created_at, updated_at) SELECT id, '(Reference) Szállítók', 'AGROPONIENTE', NOW(), NOW() FROM partners WHERE UPPER(name) = UPPER('Agroponiente Natural Produce S.L.') AND NOT EXISTS (SELECT 1 FROM partner_identifiers WHERE partner_id = partners.id AND id_type = '(Reference) Szállítók' AND value = 'AGROPONIENTE') LIMIT 1;
INSERT INTO partner_identifiers (partner_id, id_type, value, created_at, updated_at) SELECT id, '(Reference) Szállítók', 'AGROPONIENTE NIJAR', NOW(), NOW() FROM partners WHERE UPPER(name) = UPPER('Agroponiente Natural Produce S.L.') AND NOT EXISTS (SELECT 1 FROM partner_identifiers WHERE partner_id = partners.id AND id_type = '(Reference) Szállítók' AND value = 'AGROPONIENTE NIJAR') LIMIT 1;
INSERT INTO partner_identifiers (partner_id, id_type, value, created_at, updated_at) SELECT id, '(Reference) Szállítók', 'CASI AEROPORTO', NOW(), NOW() FROM partners WHERE UPPER(name) = UPPER('CASI') AND NOT EXISTS (SELECT 1 FROM partner_identifiers WHERE partner_id = partners.id AND id_type = '(Reference) Szállítók' AND value = 'CASI AEROPORTO') LIMIT 1;
INSERT INTO partner_identifiers (partner_id, id_type, value, created_at, updated_at) SELECT id, '(Reference) Szállítók', 'CASI AIRPORT', NOW(), NOW() FROM partners WHERE UPPER(name) = UPPER('CASI') AND NOT EXISTS (SELECT 1 FROM partner_identifiers WHERE partner_id = partners.id AND id_type = '(Reference) Szállítók' AND value = 'CASI AIRPORT') LIMIT 1;
INSERT INTO partner_identifiers (partner_id, id_type, value, created_at, updated_at) SELECT id, '(Reference) Szállítók', 'OLASO', NOW(), NOW() FROM partners WHERE UPPER(name) = UPPER('OLASO') AND NOT EXISTS (SELECT 1 FROM partner_identifiers WHERE partner_id = partners.id AND id_type = '(Reference) Szállítók' AND value = 'OLASO') LIMIT 1;
INSERT INTO partner_identifiers (partner_id, id_type, value, created_at, updated_at) SELECT id, '(Reference) Szállítók', 'WRAPPING', NOW(), NOW() FROM partners WHERE UPPER(name) = UPPER('WRAPPING') AND NOT EXISTS (SELECT 1 FROM partner_identifiers WHERE partner_id = partners.id AND id_type = '(Reference) Szállítók' AND value = 'WRAPPING') LIMIT 1;

COMMIT;